### ISSUE TITLE
Using immutable class instances for persistence

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-kotlin#1]
Using immutable entities as described in https://docs.spring.io/spring-framework/docs/5.0.0.BUILD-SNAPSHOT/spring-framework-reference/kotlin.html#using-immutable-class-instances-for-persistence as suggested by @sdeleuze

**Comment by sdeleuze** [comment]
Please let me know if you face blocking issues. This may impact application software design but I think it will lead to more idiomatic Kotlin code.

**Comment by arey** [comment]
Petclinic is a CRUD application (ie. users could change pet's name or add a visit). So I'm wondering if it makes sense to use immutable entities?
Maybe only the Vet entity that is just read from the database? I've tried, it's working, but I should let the var keyword due to XML marshalling (http://localhost:8080/vets.xml)
@sdeleuze what do you suggest?

**Comment by sdeleuze** [comment]
Even for CRUD application, I think it make sense yes. The trick is use data classes + their `copy()` as following:

```
val seb = User("Sébastien", "Deleuze", LocalDate.now())
val fred = seb.copy(firstName = "Frédéric")
```

Could you please give more details about the thing that make `var` mandatory with XML marshalling? Maybe Jackson non-blocking XML upcoming support could help since it should support same POJO than current JSON support. If so please add your :+1: to https://github.com/FasterXML/jackson-dataformat-xml/issues/260 and https://jira.spring.io/browse/SPR-15697.

**Comment by arey** [comment]
I'm trying to convert the Visit entity to an immutable class. Its parent class NamedEntity remains unchanged:
```
@Entity
@Table(name = "visits")
class Visit(

        @Column(name = "visit_date")
        @Temporal(TemporalType.TIMESTAMP)
        @DateTimeFormat(pattern = "yyyy-MM-dd")
        val date: Date = Date(),

        @NotEmpty
        @Column(name = "description")
        val description: String? = null,

        @Column(name = "pet_id")
        val petId: Int? = null

) : BaseEntity()
```
The unit test VisitControllerTest::testProcessNewVisitFormHasErrors failed due to Bean Validation.
It looks like Hibernate Validator do not see the NotEmpty annotation. The condtraints list remains empty:
<img width="1096" alt="visit-description-constraints" src="https://user-images.githubusercontent.com/838318/31241528-5dfb12f2-aa04-11e7-9237-47a3c26ca2e6.png">

Do you have an idea? Are Bean Validation and @Valid supported with immutable class?

**Comment by sdeleuze** [comment]
You could maybe try to compare bytecode -> Java code via IDEA (menu Tools -> Kotlin -> Show Kotlin bytecode) to the original Java code, and see where the annotation is placed.

**Comment by arey** [comment]
By decompiling the Kotlin bytecode, I've found that the ```@NotEmpty``` annotation of the Owner's firstName was put on the Owner constructor and not the property nor the getter/setter.
Removing the ```data``` keyword of the data class does not changed anything.
Maybe due to the ```@Target({CONSTRUCTOR,  ...})``` of ```NotEmpty``` ?
The ```@Column``` annotation have the expected behavior.

Kotlin code:
```
data class Owner(
...
        @Column(name = "first_name")
        @NotEmpty
        val firstName: String = "",
```

Decompiled code:
```
   @Column( name = "last_name")
   @NotNull
   private final String lastName;
...
public Owner(@Nullable Integer id, @NotEmpty @NotNull String firstName, @NotEmpty @NotNull String lastName, @NotEmpty @NotNull String address, @NotEmpty @NotNull String city, @NotEmpty @Digits(fraction = 0,integer = 10) @NotNull String telephone, @NotNull List pets) {
      Intrinsics.checkParameterIsNotNull(firstName, "firstName");
      Intrinsics.checkParameterIsNotNull(lastName, "lastName");
      Intrinsics.checkParameterIsNotNull(address, "address");
      Intrinsics.checkParameterIsNotNull(city, "city");
      Intrinsics.checkParameterIsNotNull(telephone, "telephone");
      Intrinsics.checkParameterIsNotNull(pets, "pets");
      super();
      this.id = id;
      this.firstName = firstName;
      this.lastName = lastName;
      this.address = address;
      this.city = city;
      this.telephone = telephone;
      this.pets = pets;
   }
...
   @NotNull
   public final String getLastName() {
      return this.lastName;
   }
```
Is there a way to change this behaviour?

**Comment by arey** [comment]
Maybe an answer: https://stackoverflow.com/questions/35847763/kotlin-data-class-bean-validation-jsr-303

**Comment by sdeleuze** [comment]
@apatrida has usually the answer to tricky questions ;-)

**Comment by arey** [comment]
@sdeleuze I've pushed the feature/immutable branch. Do you may have a look?

Some properties remains mutable:
* id of entity
* Pet::owner property (bi-directional relationship)
* Vets:vetList (for JAXB marshalling)
* Visit::description and Visit:date (I'm blocking)

To use data classes and the copy method, I have to remove inheritance.

**Comment by sdeleuze** [comment]
Thanks I will have a look.

**Comment by sdeleuze** [comment]
Ok, I had a look and indeed with current architecture it is not straighforward since the application is not designed for that.

Something to fix IMO is to use `org.jetbrains.kotlin.plugin.jpa` instead of `org.jetbrains.kotlin.plugin.noarg` in order to get it applied automatically to JPA entities, see [this documentation](https://kotlinlang.org/docs/reference/compiler-plugins.html#kotlin-jpa-compiler-plugin) for more details.

The second point in order to allow more idiomatic Kotlin design is to split entities and DTO used for the forms. I think I would do like what I did on MiXiT, create clean entity data classes with most fields non nul `val` and use extensions on controller side to switch from DTO to entities, see https://github.com/mixitconf/mixit/blob/master/src/main/kotlin/mixit/model/User.kt and https://github.com/mixitconf/mixit/blob/master/src/main/kotlin/mixit/web/handler/UserHandler.kt#L44-L61.

Any thoughts?

**Comment by arey** [comment]
Thank you Sébastien for the review.

I've removed the noarg plugin and the application works fine.
A default constructor is generated even if I remove the Spring plugin (but as expected, tests failed):
```
  public Pet() {
      this((Integer)null, (String)null, (Date)null, (PetType)null, (Owner)null, (Set)null, 63, (DefaultConstructorMarker)null);
   }
```

I have to think about changing the application architecture by introducing a DTO layer and an objet-to-object mapping like you've done into the MiXiT website. Used both in the persistance and the presentation layer, Bean Validation constraints should to be duplicated. Petclinic is a very simple application. And in this case, I'de like to use Domain Object in most layers.

**Comment by arey** [comment]
Intersting feedback "Hibernate with Kotlin – powered by Spring Boot":
https://kotlinexpertise.com/hibernate-with-kotlin-spring-boot/
